export const ISO2Continents = {
  BD: 'AS',
  BE: 'EU',
  BF: 'AF',
  BG: 'EU',
  BA: 'EU',
  BB: 'NA',
  WF: 'OC',
  BL: 'NA',
  BM: 'NA',
  BN: 'AS',
  BO: 'SA',
  BH: 'AS',
  BI: 'AF',
  BJ: 'AF',
  BT: 'AS',
  JM: 'NA',
  BV: 'AN',
  BW: 'AF',
  WS: 'OC',
  BQ: 'NA',
  BR: 'SA',
  BS: 'NA',
  JE: 'EU',
  BY: 'EU',
  BZ: 'NA',
  RU: 'EU',
  RW: 'AF',
  RS: 'EU',
  TL: 'OC',
  RE: 'AF',
  TM: 'AS',
  TJ: 'AS',
  RO: 'EU',
  TK: 'OC',
  GW: 'AF',
  GU: 'OC',
  GT: 'NA',
  GS: 'AN',
  GR: 'EU',
  GQ: 'AF',
  GP: 'NA',
  JP: 'AS',
  GY: 'SA',
  GG: 'EU',
  GF: 'SA',
  GE: 'AS',
  GD: 'NA',
  GB: 'EU',
  GA: 'AF',
  SV: 'NA',
  GN: 'AF',
  GM: 'AF',
  GL: 'NA',
  GI: 'EU',
  GH: 'AF',
  OM: 'AS',
  TN: 'AF',
  JO: 'AS',
  HR: 'EU',
  HT: 'NA',
  HU: 'EU',
  HK: 'AS',
  HN: 'NA',
  HM: 'AN',
  VE: 'SA',
  PR: 'NA',
  PS: 'AS',
  PW: 'OC',
  PT: 'EU',
  SJ: 'EU',
  PY: 'SA',
  IQ: 'AS',
  PA: 'NA',
  PF: 'OC',
  PG: 'OC',
  PE: 'SA',
  PK: 'AS',
  PH: 'AS',
  PN: 'OC',
  PL: 'EU',
  PM: 'NA',
  ZM: 'AF',
  EH: 'AF',
  EE: 'EU',
  EG: 'AF',
  ZA: 'AF',
  EC: 'SA',
  IT: 'EU',
  VN: 'AS',
  SB: 'OC',
  ET: 'AF',
  SO: 'AF',
  ZW: 'AF',
  SA: 'AS',
  ES: 'EU',
  ER: 'AF',
  ME: 'EU',
  MD: 'EU',
  MG: 'AF',
  MF: 'NA',
  MA: 'AF',
  MC: 'EU',
  UZ: 'AS',
  MM: 'AS',
  ML: 'AF',
  MO: 'AS',
  MN: 'AS',
  MH: 'OC',
  MK: 'EU',
  MU: 'AF',
  MT: 'EU',
  MW: 'AF',
  MV: 'AS',
  MQ: 'NA',
  MP: 'OC',
  MS: 'NA',
  MR: 'AF',
  IM: 'EU',
  UG: 'AF',
  TZ: 'AF',
  MY: 'AS',
  MX: 'NA',
  IL: 'AS',
  FR: 'EU',
  IO: 'AS',
  SH: 'AF',
  FI: 'EU',
  FJ: 'OC',
  FK: 'SA',
  FM: 'OC',
  FO: 'EU',
  NI: 'NA',
  NL: 'EU',
  NO: 'EU',
  NA: 'AF',
  VU: 'OC',
  NC: 'OC',
  NE: 'AF',
  NF: 'OC',
  NG: 'AF',
  NZ: 'OC',
  NP: 'AS',
  NR: 'OC',
  NU: 'OC',
  CK: 'OC',
  XK: 'EU',
  CI: 'AF',
  CH: 'EU',
  CO: 'SA',
  CN: 'AS',
  CM: 'AF',
  CL: 'SA',
  CC: 'AS',
  CA: 'NA',
  CG: 'AF',
  CF: 'AF',
  CD: 'AF',
  CZ: 'EU',
  CY: 'EU',
  CX: 'AS',
  CR: 'NA',
  CW: 'NA',
  CV: 'AF',
  CU: 'NA',
  SZ: 'AF',
  SY: 'AS',
  SX: 'NA',
  KG: 'AS',
  KE: 'AF',
  SS: 'AF',
  SR: 'SA',
  KI: 'OC',
  KH: 'AS',
  KN: 'NA',
  KM: 'AF',
  ST: 'AF',
  SK: 'EU',
  KR: 'AS',
  SI: 'EU',
  KP: 'AS',
  KW: 'AS',
  SN: 'AF',
  SM: 'EU',
  SL: 'AF',
  SC: 'AF',
  KZ: 'AS',
  KY: 'NA',
  SG: 'AS',
  SE: 'EU',
  SD: 'AF',
  DO: 'NA',
  DM: 'NA',
  DJ: 'AF',
  DK: 'EU',
  VG: 'NA',
  DE: 'EU',
  YE: 'AS',
  DZ: 'AF',
  US: 'NA',
  UY: 'SA',
  YT: 'AF',
  UM: 'OC',
  LB: 'AS',
  LC: 'NA',
  LA: 'AS',
  TV: 'OC',
  TW: 'AS',
  TT: 'NA',
  TR: 'AS',
  LK: 'AS',
  LI: 'EU',
  LV: 'EU',
  TO: 'OC',
  LT: 'EU',
  LU: 'EU',
  LR: 'AF',
  LS: 'AF',
  TH: 'AS',
  TF: 'AN',
  TG: 'AF',
  TD: 'AF',
  TC: 'NA',
  LY: 'AF',
  VA: 'EU',
  VC: 'NA',
  AE: 'AS',
  AD: 'EU',
  AG: 'NA',
  AF: 'AS',
  AI: 'NA',
  VI: 'NA',
  IS: 'EU',
  IR: 'AS',
  AM: 'AS',
  AL: 'EU',
  AO: 'AF',
  AQ: 'AN',
  AS: 'OC',
  AR: 'SA',
  AU: 'OC',
  AT: 'EU',
  AW: 'NA',
  IN: 'AS',
  AX: 'EU',
  AZ: 'AS',
  IE: 'EU',
  ID: 'AS',
  UA: 'EU',
  QA: 'AS',
  MZ: 'AF',
};

/**
 * Mapping of ISO2 country codes to country names
 */
export const ISO2CountryNames = {
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  WF: 'Wallis and Futuna',
  BL: 'Saint Barthelemy',
  BM: 'Bermuda',
  BN: 'Brunei',
  BO: 'Bolivia',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BT: 'Bhutan',
  JM: 'Jamaica',
  BV: 'Bouvet Island',
  BW: 'Botswana',
  WS: 'Samoa',
  BQ: 'Bonaire, Saint Eustatius and Saba ',
  BR: 'Brazil',
  BS: 'Bahamas',
  JE: 'Jersey',
  BY: 'Belarus',
  BZ: 'Belize',
  RU: 'Russia',
  RW: 'Rwanda',
  RS: 'Serbia',
  TL: 'East Timor',
  RE: 'Reunion',
  TM: 'Turkmenistan',
  TJ: 'Tajikistan',
  RO: 'Romania',
  TK: 'Tokelau',
  GW: 'Guinea-Bissau',
  GU: 'Guam',
  GT: 'Guatemala',
  GS: 'South Georgia and the South Sandwich Islands',
  GR: 'Greece',
  GQ: 'Equatorial Guinea',
  GP: 'Guadeloupe',
  JP: 'Japan',
  GY: 'Guyana',
  GG: 'Guernsey',
  GF: 'French Guiana',
  GE: 'Georgia',
  GD: 'Grenada',
  GB: 'United Kingdom',
  GA: 'Gabon',
  SV: 'El Salvador',
  GN: 'Guinea',
  GM: 'Gambia',
  GL: 'Greenland',
  GI: 'Gibraltar',
  GH: 'Ghana',
  OM: 'Oman',
  TN: 'Tunisia',
  JO: 'Jordan',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HM: 'Heard Island and McDonald Islands',
  VE: 'Venezuela',
  PR: 'Puerto Rico',
  PS: 'Palestinian Territory',
  PW: 'Palau',
  PT: 'Portugal',
  SJ: 'Svalbard and Jan Mayen',
  PY: 'Paraguay',
  IQ: 'Iraq',
  PA: 'Panama',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PE: 'Peru',
  PK: 'Pakistan',
  PH: 'Philippines',
  PN: 'Pitcairn',
  PL: 'Poland',
  PM: 'Saint Pierre and Miquelon',
  ZM: 'Zambia',
  EH: 'Western Sahara',
  EE: 'Estonia',
  EG: 'Egypt',
  ZA: 'South Africa',
  EC: 'Ecuador',
  IT: 'Italy',
  VN: 'Vietnam',
  SB: 'Solomon Islands',
  ET: 'Ethiopia',
  SO: 'Somalia',
  ZW: 'Zimbabwe',
  SA: 'Saudi Arabia',
  ES: 'Spain',
  ER: 'Eritrea',
  ME: 'Montenegro',
  MD: 'Moldova',
  MG: 'Madagascar',
  MF: 'Saint Martin',
  MA: 'Morocco',
  MC: 'Monaco',
  UZ: 'Uzbekistan',
  MM: 'Myanmar',
  ML: 'Mali',
  MO: 'Macao',
  MN: 'Mongolia',
  MH: 'Marshall Islands',
  MK: 'Macedonia',
  MU: 'Mauritius',
  MT: 'Malta',
  MW: 'Malawi',
  MV: 'Maldives',
  MQ: 'Martinique',
  MP: 'Northern Mariana Islands',
  MS: 'Montserrat',
  MR: 'Mauritania',
  IM: 'Isle of Man',
  UG: 'Uganda',
  TZ: 'Tanzania',
  MY: 'Malaysia',
  MX: 'Mexico',
  IL: 'Israel',
  FR: 'France',
  IO: 'British Indian Ocean Territory',
  SH: 'Saint Helena',
  FI: 'Finland',
  FJ: 'Fiji',
  FK: 'Falkland Islands',
  FM: 'Micronesia',
  FO: 'Faroe Islands',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NA: 'Namibia',
  VU: 'Vanuatu',
  NC: 'New Caledonia',
  NE: 'Niger',
  NF: 'Norfolk Island',
  NG: 'Nigeria',
  NZ: 'New Zealand',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  CK: 'Cook Islands',
  XK: 'Kosovo',
  CI: 'Ivory Coast',
  CH: 'Switzerland',
  CO: 'Colombia',
  CN: 'China',
  CM: 'Cameroon',
  CL: 'Chile',
  CC: 'Cocos Islands',
  CA: 'Canada',
  CG: 'Republic of the Congo',
  CF: 'Central African Republic',
  CD: 'Democratic Republic of the Congo',
  CZ: 'Czech Republic',
  CY: 'Cyprus',
  CX: 'Christmas Island',
  CR: 'Costa Rica',
  CW: 'Curacao',
  CV: 'Cape Verde',
  CU: 'Cuba',
  SZ: 'Swaziland',
  SY: 'Syria',
  SX: 'Sint Maarten',
  KG: 'Kyrgyzstan',
  KE: 'Kenya',
  SS: 'South Sudan',
  SR: 'Suriname',
  KI: 'Kiribati',
  KH: 'Cambodia',
  KN: 'Saint Kitts and Nevis',
  KM: 'Comoros',
  ST: 'Sao Tome and Principe',
  SK: 'Slovakia',
  KR: 'South Korea',
  SI: 'Slovenia',
  KP: 'North Korea',
  KW: 'Kuwait',
  SN: 'Senegal',
  SM: 'San Marino',
  SL: 'Sierra Leone',
  SC: 'Seychelles',
  KZ: 'Kazakhstan',
  KY: 'Cayman Islands',
  SG: 'Singapore',
  SE: 'Sweden',
  SD: 'Sudan',
  DO: 'Dominican Republic',
  DM: 'Dominica',
  DJ: 'Djibouti',
  DK: 'Denmark',
  VG: 'British Virgin Islands',
  DE: 'Germany',
  YE: 'Yemen',
  DZ: 'Algeria',
  US: 'United States',
  UY: 'Uruguay',
  YT: 'Mayotte',
  UM: 'United States Minor Outlying Islands',
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LA: 'Laos',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  TT: 'Trinidad and Tobago',
  TR: 'Turkey',
  LK: 'Sri Lanka',
  LI: 'Liechtenstein',
  LV: 'Latvia',
  TO: 'Tonga',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LR: 'Liberia',
  LS: 'Lesotho',
  TH: 'Thailand',
  TF: 'French Southern Territories',
  TG: 'Togo',
  TD: 'Chad',
  TC: 'Turks and Caicos Islands',
  LY: 'Libya',
  VA: 'Vatican',
  VC: 'Saint Vincent and the Grenadines',
  AE: 'United Arab Emirates',
  AD: 'Andorra',
  AG: 'Antigua and Barbuda',
  AF: 'Afghanistan',
  AI: 'Anguilla',
  VI: 'U.S. Virgin Islands',
  IS: 'Iceland',
  IR: 'Iran',
  AM: 'Armenia',
  AL: 'Albania',
  AO: 'Angola',
  AQ: 'Antarctica',
  AS: 'American Samoa',
  AR: 'Argentina',
  AU: 'Australia',
  AT: 'Austria',
  AW: 'Aruba',
  IN: 'India',
  AX: 'Aland Islands',
  AZ: 'Azerbaijan',
  IE: 'Ireland',
  ID: 'Indonesia',
  UA: 'Ukraine',
  QA: 'Qatar',
  MZ: 'Mozambique',
};

export const ISO2ISO3 = {
  BD: 'BGD',
  BE: 'BEL',
  BF: 'BFA',
  BG: 'BGR',
  BA: 'BIH',
  BB: 'BRB',
  WF: 'WLF',
  BL: 'BLM',
  BM: 'BMU',
  BN: 'BRN',
  BO: 'BOL',
  BH: 'BHR',
  BI: 'BDI',
  BJ: 'BEN',
  BT: 'BTN',
  JM: 'JAM',
  BV: 'BVT',
  BW: 'BWA',
  WS: 'WSM',
  BQ: 'BES',
  BR: 'BRA',
  BS: 'BHS',
  JE: 'JEY',
  BY: 'BLR',
  BZ: 'BLZ',
  RU: 'RUS',
  RW: 'RWA',
  RS: 'SRB',
  TL: 'TLS',
  RE: 'REU',
  TM: 'TKM',
  TJ: 'TJK',
  RO: 'ROU',
  TK: 'TKL',
  GW: 'GNB',
  GU: 'GUM',
  GT: 'GTM',
  GS: 'SGS',
  GR: 'GRC',
  GQ: 'GNQ',
  GP: 'GLP',
  JP: 'JPN',
  GY: 'GUY',
  GG: 'GGY',
  GF: 'GUF',
  GE: 'GEO',
  GD: 'GRD',
  GB: 'GBR',
  GA: 'GAB',
  SV: 'SLV',
  GN: 'GIN',
  GM: 'GMB',
  GL: 'GRL',
  GI: 'GIB',
  GH: 'GHA',
  OM: 'OMN',
  TN: 'TUN',
  JO: 'JOR',
  HR: 'HRV',
  HT: 'HTI',
  HU: 'HUN',
  HK: 'HKG',
  HN: 'HND',
  HM: 'HMD',
  VE: 'VEN',
  PR: 'PRI',
  PS: 'PSE',
  PW: 'PLW',
  PT: 'PRT',
  SJ: 'SJM',
  PY: 'PRY',
  IQ: 'IRQ',
  PA: 'PAN',
  PF: 'PYF',
  PG: 'PNG',
  PE: 'PER',
  PK: 'PAK',
  PH: 'PHL',
  PN: 'PCN',
  PL: 'POL',
  PM: 'SPM',
  ZM: 'ZMB',
  EH: 'ESH',
  EE: 'EST',
  EG: 'EGY',
  ZA: 'ZAF',
  EC: 'ECU',
  IT: 'ITA',
  VN: 'VNM',
  SB: 'SLB',
  ET: 'ETH',
  SO: 'SOM',
  ZW: 'ZWE',
  SA: 'SAU',
  ES: 'ESP',
  ER: 'ERI',
  ME: 'MNE',
  MD: 'MDA',
  MG: 'MDG',
  MF: 'MAF',
  MA: 'MAR',
  MC: 'MCO',
  UZ: 'UZB',
  MM: 'MMR',
  ML: 'MLI',
  MO: 'MAC',
  MN: 'MNG',
  MH: 'MHL',
  MK: 'MKD',
  MU: 'MUS',
  MT: 'MLT',
  MW: 'MWI',
  MV: 'MDV',
  MQ: 'MTQ',
  MP: 'MNP',
  MS: 'MSR',
  MR: 'MRT',
  IM: 'IMN',
  UG: 'UGA',
  TZ: 'TZA',
  MY: 'MYS',
  MX: 'MEX',
  IL: 'ISR',
  FR: 'FRA',
  IO: 'IOT',
  SH: 'SHN',
  FI: 'FIN',
  FJ: 'FJI',
  FK: 'FLK',
  FM: 'FSM',
  FO: 'FRO',
  NI: 'NIC',
  NL: 'NLD',
  NO: 'NOR',
  NA: 'NAM',
  VU: 'VUT',
  NC: 'NCL',
  NE: 'NER',
  NF: 'NFK',
  NG: 'NGA',
  NZ: 'NZL',
  NP: 'NPL',
  NR: 'NRU',
  NU: 'NIU',
  CK: 'COK',
  XK: 'XKX',
  CI: 'CIV',
  CH: 'CHE',
  CO: 'COL',
  CN: 'CHN',
  CM: 'CMR',
  CL: 'CHL',
  CC: 'CCK',
  CA: 'CAN',
  CG: 'COG',
  CF: 'CAF',
  CD: 'COD',
  CZ: 'CZE',
  CY: 'CYP',
  CX: 'CXR',
  CR: 'CRI',
  CW: 'CUW',
  CV: 'CPV',
  CU: 'CUB',
  SZ: 'SWZ',
  SY: 'SYR',
  SX: 'SXM',
  KG: 'KGZ',
  KE: 'KEN',
  SS: 'SSD',
  SR: 'SUR',
  KI: 'KIR',
  KH: 'KHM',
  KN: 'KNA',
  KM: 'COM',
  ST: 'STP',
  SK: 'SVK',
  KR: 'KOR',
  SI: 'SVN',
  KP: 'PRK',
  KW: 'KWT',
  SN: 'SEN',
  SM: 'SMR',
  SL: 'SLE',
  SC: 'SYC',
  KZ: 'KAZ',
  KY: 'CYM',
  SG: 'SGP',
  SE: 'SWE',
  SD: 'SDN',
  DO: 'DOM',
  DM: 'DMA',
  DJ: 'DJI',
  DK: 'DNK',
  VG: 'VGB',
  DE: 'DEU',
  YE: 'YEM',
  DZ: 'DZA',
  US: 'USA',
  UY: 'URY',
  YT: 'MYT',
  UM: 'UMI',
  LB: 'LBN',
  LC: 'LCA',
  LA: 'LAO',
  TV: 'TUV',
  TW: 'TWN',
  TT: 'TTO',
  TR: 'TUR',
  LK: 'LKA',
  LI: 'LIE',
  LV: 'LVA',
  TO: 'TON',
  LT: 'LTU',
  LU: 'LUX',
  LR: 'LBR',
  LS: 'LSO',
  TH: 'THA',
  TF: 'ATF',
  TG: 'TGO',
  TD: 'TCD',
  TC: 'TCA',
  LY: 'LBY',
  VA: 'VAT',
  VC: 'VCT',
  AE: 'ARE',
  AD: 'AND',
  AG: 'ATG',
  AF: 'AFG',
  AI: 'AIA',
  VI: 'VIR',
  IS: 'ISL',
  IR: 'IRN',
  AM: 'ARM',
  AL: 'ALB',
  AO: 'AGO',
  AQ: 'ATA',
  AS: 'ASM',
  AR: 'ARG',
  AU: 'AUS',
  AT: 'AUT',
  AW: 'ABW',
  IN: 'IND',
  AX: 'ALA',
  AZ: 'AZE',
  IE: 'IRL',
  ID: 'IDN',
  UA: 'UKR',
  QA: 'QAT',
  MZ: 'MOZ',
};

export const ISO2Currencies = {
  BD: 'BDT',
  BE: 'EUR',
  BF: 'XOF',
  BG: 'BGN',
  BA: 'BAM',
  BB: 'BBD',
  WF: 'XPF',
  BL: 'EUR',
  BM: 'BMD',
  BN: 'BND',
  BO: 'BOB',
  BH: 'BHD',
  BI: 'BIF',
  BJ: 'XOF',
  BT: 'BTN',
  JM: 'JMD',
  BV: 'NOK',
  BW: 'BWP',
  WS: 'WST',
  BQ: 'USD',
  BR: 'BRL',
  BS: 'BSD',
  JE: 'GBP',
  BY: 'BYR',
  BZ: 'BZD',
  RU: 'RUB',
  RW: 'RWF',
  RS: 'RSD',
  TL: 'USD',
  RE: 'EUR',
  TM: 'TMT',
  TJ: 'TJS',
  RO: 'RON',
  TK: 'NZD',
  GW: 'XOF',
  GU: 'USD',
  GT: 'GTQ',
  GS: 'GBP',
  GR: 'EUR',
  GQ: 'XAF',
  GP: 'EUR',
  JP: 'JPY',
  GY: 'GYD',
  GG: 'GBP',
  GF: 'EUR',
  GE: 'GEL',
  GD: 'XCD',
  GB: 'GBP',
  GA: 'XAF',
  SV: 'USD',
  GN: 'GNF',
  GM: 'GMD',
  GL: 'DKK',
  GI: 'GIP',
  GH: 'GHS',
  OM: 'OMR',
  TN: 'TND',
  JO: 'JOD',
  HR: 'HRK',
  HT: 'HTG',
  HU: 'HUF',
  HK: 'HKD',
  HN: 'HNL',
  HM: 'AUD',
  VE: 'VEF',
  PR: 'USD',
  PS: 'ILS',
  PW: 'USD',
  PT: 'EUR',
  SJ: 'NOK',
  PY: 'PYG',
  IQ: 'IQD',
  PA: 'PAB',
  PF: 'XPF',
  PG: 'PGK',
  PE: 'PEN',
  PK: 'PKR',
  PH: 'PHP',
  PN: 'NZD',
  PL: 'PLN',
  PM: 'EUR',
  ZM: 'ZMK',
  EH: 'MAD',
  EE: 'EUR',
  EG: 'EGP',
  ZA: 'ZAR',
  EC: 'USD',
  IT: 'EUR',
  VN: 'VND',
  SB: 'SBD',
  ET: 'ETB',
  SO: 'SOS',
  ZW: 'ZWL',
  SA: 'SAR',
  ES: 'EUR',
  ER: 'ERN',
  ME: 'EUR',
  MD: 'MDL',
  MG: 'MGA',
  MF: 'EUR',
  MA: 'MAD',
  MC: 'EUR',
  UZ: 'UZS',
  MM: 'MMK',
  ML: 'XOF',
  MO: 'MOP',
  MN: 'MNT',
  MH: 'USD',
  MK: 'MKD',
  MU: 'MUR',
  MT: 'EUR',
  MW: 'MWK',
  MV: 'MVR',
  MQ: 'EUR',
  MP: 'USD',
  MS: 'XCD',
  MR: 'MRO',
  IM: 'GBP',
  UG: 'UGX',
  TZ: 'TZS',
  MY: 'MYR',
  MX: 'MXN',
  IL: 'ILS',
  FR: 'EUR',
  IO: 'USD',
  SH: 'SHP',
  FI: 'EUR',
  FJ: 'FJD',
  FK: 'FKP',
  FM: 'USD',
  FO: 'DKK',
  NI: 'NIO',
  NL: 'EUR',
  NO: 'NOK',
  NA: 'NAD',
  VU: 'VUV',
  NC: 'XPF',
  NE: 'XOF',
  NF: 'AUD',
  NG: 'NGN',
  NZ: 'NZD',
  NP: 'NPR',
  NR: 'AUD',
  NU: 'NZD',
  CK: 'NZD',
  XK: 'EUR',
  CI: 'XOF',
  CH: 'CHF',
  CO: 'COP',
  CN: 'CNY',
  CM: 'XAF',
  CL: 'CLP',
  CC: 'AUD',
  CA: 'CAD',
  CG: 'XAF',
  CF: 'XAF',
  CD: 'CDF',
  CZ: 'CZK',
  CY: 'EUR',
  CX: 'AUD',
  CR: 'CRC',
  CW: 'ANG',
  CV: 'CVE',
  CU: 'CUP',
  SZ: 'SZL',
  SY: 'SYP',
  SX: 'ANG',
  KG: 'KGS',
  KE: 'KES',
  SS: 'SSP',
  SR: 'SRD',
  KI: 'AUD',
  KH: 'KHR',
  KN: 'XCD',
  KM: 'KMF',
  ST: 'STD',
  SK: 'EUR',
  KR: 'KRW',
  SI: 'EUR',
  KP: 'KPW',
  KW: 'KWD',
  SN: 'XOF',
  SM: 'EUR',
  SL: 'SLL',
  SC: 'SCR',
  KZ: 'KZT',
  KY: 'KYD',
  SG: 'SGD',
  SE: 'SEK',
  SD: 'SDG',
  DO: 'DOP',
  DM: 'XCD',
  DJ: 'DJF',
  DK: 'DKK',
  VG: 'USD',
  DE: 'EUR',
  YE: 'YER',
  DZ: 'DZD',
  US: 'USD',
  UY: 'UYU',
  YT: 'EUR',
  UM: 'USD',
  LB: 'LBP',
  LC: 'XCD',
  LA: 'LAK',
  TV: 'AUD',
  TW: 'TWD',
  TT: 'TTD',
  TR: 'TRY',
  LK: 'LKR',
  LI: 'CHF',
  LV: 'EUR',
  TO: 'TOP',
  LT: 'LTL',
  LU: 'EUR',
  LR: 'LRD',
  LS: 'LSL',
  TH: 'THB',
  TF: 'EUR',
  TG: 'XOF',
  TD: 'XAF',
  TC: 'USD',
  LY: 'LYD',
  VA: 'EUR',
  VC: 'XCD',
  AE: 'AED',
  AD: 'EUR',
  AG: 'XCD',
  AF: 'AFN',
  AI: 'XCD',
  VI: 'USD',
  IS: 'ISK',
  IR: 'IRR',
  AM: 'AMD',
  AL: 'ALL',
  AO: 'AOA',
  AQ: '',
  AS: 'USD',
  AR: 'ARS',
  AU: 'AUD',
  AT: 'EUR',
  AW: 'AWG',
  IN: 'INR',
  AX: 'EUR',
  AZ: 'AZN',
  IE: 'EUR',
  ID: 'IDR',
  UA: 'UAH',
  QA: 'QAR',
  MZ: 'MZN',
};

export const ISO2DialingCodes = {
  BD: '880',
  BE: '32',
  BF: '226',
  BG: '359',
  BA: '387',
  BB: '+1-246',
  WF: '681',
  BL: '590',
  BM: '+1-441',
  BN: '673',
  BO: '591',
  BH: '973',
  BI: '257',
  BJ: '229',
  BT: '975',
  JM: '+1-876',
  BV: '',
  BW: '267',
  WS: '685',
  BQ: '599',
  BR: '55',
  BS: '+1-242',
  JE: '+44-1534',
  BY: '375',
  BZ: '501',
  RU: '7',
  RW: '250',
  RS: '381',
  TL: '670',
  RE: '262',
  TM: '993',
  TJ: '992',
  RO: '40',
  TK: '690',
  GW: '245',
  GU: '+1-671',
  GT: '502',
  GS: '',
  GR: '30',
  GQ: '240',
  GP: '590',
  JP: '81',
  GY: '592',
  GG: '+44-1481',
  GF: '594',
  GE: '995',
  GD: '+1-473',
  GB: '44',
  GA: '241',
  SV: '503',
  GN: '224',
  GM: '220',
  GL: '299',
  GI: '350',
  GH: '233',
  OM: '968',
  TN: '216',
  JO: '962',
  HR: '385',
  HT: '509',
  HU: '36',
  HK: '852',
  HN: '504',
  HM: ' ',
  VE: '58',
  PR: '+1-787 and 1-939',
  PS: '970',
  PW: '680',
  PT: '351',
  SJ: '47',
  PY: '595',
  IQ: '964',
  PA: '507',
  PF: '689',
  PG: '675',
  PE: '51',
  PK: '92',
  PH: '63',
  PN: '870',
  PL: '48',
  PM: '508',
  ZM: '260',
  EH: '212',
  EE: '372',
  EG: '20',
  ZA: '27',
  EC: '593',
  IT: '39',
  VN: '84',
  SB: '677',
  ET: '251',
  SO: '252',
  ZW: '263',
  SA: '966',
  ES: '34',
  ER: '291',
  ME: '382',
  MD: '373',
  MG: '261',
  MF: '590',
  MA: '212',
  MC: '377',
  UZ: '998',
  MM: '95',
  ML: '223',
  MO: '853',
  MN: '976',
  MH: '692',
  MK: '389',
  MU: '230',
  MT: '356',
  MW: '265',
  MV: '960',
  MQ: '596',
  MP: '+1-670',
  MS: '+1-664',
  MR: '222',
  IM: '+44-1624',
  UG: '256',
  TZ: '255',
  MY: '60',
  MX: '52',
  IL: '972',
  FR: '33',
  IO: '246',
  SH: '290',
  FI: '358',
  FJ: '679',
  FK: '500',
  FM: '691',
  FO: '298',
  NI: '505',
  NL: '31',
  NO: '47',
  NA: '264',
  VU: '678',
  NC: '687',
  NE: '227',
  NF: '672',
  NG: '234',
  NZ: '64',
  NP: '977',
  NR: '674',
  NU: '683',
  CK: '682',
  XK: '',
  CI: '225',
  CH: '41',
  CO: '57',
  CN: '86',
  CM: '237',
  CL: '56',
  CC: '61',
  CA: '1',
  CG: '242',
  CF: '236',
  CD: '243',
  CZ: '420',
  CY: '357',
  CX: '61',
  CR: '506',
  CW: '599',
  CV: '238',
  CU: '53',
  SZ: '268',
  SY: '963',
  SX: '599',
  KG: '996',
  KE: '254',
  SS: '211',
  SR: '597',
  KI: '686',
  KH: '855',
  KN: '+1-869',
  KM: '269',
  ST: '239',
  SK: '421',
  KR: '82',
  SI: '386',
  KP: '850',
  KW: '965',
  SN: '221',
  SM: '378',
  SL: '232',
  SC: '248',
  KZ: '7',
  KY: '+1-345',
  SG: '65',
  SE: '46',
  SD: '249',
  DO: '+1-809 and 1-829',
  DM: '+1-767',
  DJ: '253',
  DK: '45',
  VG: '+1-284',
  DE: '49',
  YE: '967',
  DZ: '213',
  US: '1',
  UY: '598',
  YT: '262',
  UM: '1',
  LB: '961',
  LC: '+1-758',
  LA: '856',
  TV: '688',
  TW: '886',
  TT: '+1-868',
  TR: '90',
  LK: '94',
  LI: '423',
  LV: '371',
  TO: '676',
  LT: '370',
  LU: '352',
  LR: '231',
  LS: '266',
  TH: '66',
  TF: '',
  TG: '228',
  TD: '235',
  TC: '+1-649',
  LY: '218',
  VA: '379',
  VC: '+1-784',
  AE: '971',
  AD: '376',
  AG: '+1-268',
  AF: '93',
  AI: '+1-264',
  VI: '+1-340',
  IS: '354',
  IR: '98',
  AM: '374',
  AL: '355',
  AO: '244',
  AQ: '',
  AS: '+1-684',
  AR: '54',
  AU: '61',
  AT: '43',
  AW: '297',
  IN: '91',
  AX: '+358-18',
  AZ: '994',
  IE: '353',
  ID: '62',
  UA: '380',
  QA: '974',
  MZ: '258',
};

export const ISO2CapitalCities = {
  BD: 'Dhaka',
  BE: 'Brussels',
  BF: 'Ouagadougou',
  BG: 'Sofia',
  BA: 'Sarajevo',
  BB: 'Bridgetown',
  WF: 'Mata Utu',
  BL: 'Gustavia',
  BM: 'Hamilton',
  BN: 'Bandar Seri Begawan',
  BO: 'Sucre',
  BH: 'Manama',
  BI: 'Bujumbura',
  BJ: 'Porto-Novo',
  BT: 'Thimphu',
  JM: 'Kingston',
  BV: '',
  BW: 'Gaborone',
  WS: 'Apia',
  BQ: '',
  BR: 'Brasilia',
  BS: 'Nassau',
  JE: 'Saint Helier',
  BY: 'Minsk',
  BZ: 'Belmopan',
  RU: 'Moscow',
  RW: 'Kigali',
  RS: 'Belgrade',
  TL: 'Dili',
  RE: 'Saint-Denis',
  TM: 'Ashgabat',
  TJ: 'Dushanbe',
  RO: 'Bucharest',
  TK: '',
  GW: 'Bissau',
  GU: 'Hagatna',
  GT: 'Guatemala City',
  GS: 'Grytviken',
  GR: 'Athens',
  GQ: 'Malabo',
  GP: 'Basse-Terre',
  JP: 'Tokyo',
  GY: 'Georgetown',
  GG: 'St Peter Port',
  GF: 'Cayenne',
  GE: 'Tbilisi',
  GD: "St. George's",
  GB: 'London',
  GA: 'Libreville',
  SV: 'San Salvador',
  GN: 'Conakry',
  GM: 'Banjul',
  GL: 'Nuuk',
  GI: 'Gibraltar',
  GH: 'Accra',
  OM: 'Muscat',
  TN: 'Tunis',
  JO: 'Amman',
  HR: 'Zagreb',
  HT: 'Port-au-Prince',
  HU: 'Budapest',
  HK: 'Hong Kong',
  HN: 'Tegucigalpa',
  HM: '',
  VE: 'Caracas',
  PR: 'San Juan',
  PS: 'East Jerusalem',
  PW: 'Melekeok',
  PT: 'Lisbon',
  SJ: 'Longyearbyen',
  PY: 'Asuncion',
  IQ: 'Baghdad',
  PA: 'Panama City',
  PF: 'Papeete',
  PG: 'Port Moresby',
  PE: 'Lima',
  PK: 'Islamabad',
  PH: 'Manila',
  PN: 'Adamstown',
  PL: 'Warsaw',
  PM: 'Saint-Pierre',
  ZM: 'Lusaka',
  EH: 'El-Aaiun',
  EE: 'Tallinn',
  EG: 'Cairo',
  ZA: 'Pretoria',
  EC: 'Quito',
  IT: 'Rome',
  VN: 'Hanoi',
  SB: 'Honiara',
  ET: 'Addis Ababa',
  SO: 'Mogadishu',
  ZW: 'Harare',
  SA: 'Riyadh',
  ES: 'Madrid',
  ER: 'Asmara',
  ME: 'Podgorica',
  MD: 'Chisinau',
  MG: 'Antananarivo',
  MF: 'Marigot',
  MA: 'Rabat',
  MC: 'Monaco',
  UZ: 'Tashkent',
  MM: 'Nay Pyi Taw',
  ML: 'Bamako',
  MO: 'Macao',
  MN: 'Ulan Bator',
  MH: 'Majuro',
  MK: 'Skopje',
  MU: 'Port Louis',
  MT: 'Valletta',
  MW: 'Lilongwe',
  MV: 'Male',
  MQ: 'Fort-de-France',
  MP: 'Saipan',
  MS: 'Plymouth',
  MR: 'Nouakchott',
  IM: 'Douglas, Isle of Man',
  UG: 'Kampala',
  TZ: 'Dodoma',
  MY: 'Kuala Lumpur',
  MX: 'Mexico City',
  IL: 'Jerusalem',
  FR: 'Paris',
  IO: 'Diego Garcia',
  SH: 'Jamestown',
  FI: 'Helsinki',
  FJ: 'Suva',
  FK: 'Stanley',
  FM: 'Palikir',
  FO: 'Torshavn',
  NI: 'Managua',
  NL: 'Amsterdam',
  NO: 'Oslo',
  NA: 'Windhoek',
  VU: 'Port Vila',
  NC: 'Noumea',
  NE: 'Niamey',
  NF: 'Kingston',
  NG: 'Abuja',
  NZ: 'Wellington',
  NP: 'Kathmandu',
  NR: 'Yaren',
  NU: 'Alofi',
  CK: 'Avarua',
  XK: 'Pristina',
  CI: 'Yamoussoukro',
  CH: 'Berne',
  CO: 'Bogota',
  CN: 'Beijing',
  CM: 'Yaounde',
  CL: 'Santiago',
  CC: 'West Island',
  CA: 'Ottawa',
  CG: 'Brazzaville',
  CF: 'Bangui',
  CD: 'Kinshasa',
  CZ: 'Prague',
  CY: 'Nicosia',
  CX: 'Flying Fish Cove',
  CR: 'San Jose',
  CW: ' Willemstad',
  CV: 'Praia',
  CU: 'Havana',
  SZ: 'Mbabane',
  SY: 'Damascus',
  SX: 'Philipsburg',
  KG: 'Bishkek',
  KE: 'Nairobi',
  SS: 'Juba',
  SR: 'Paramaribo',
  KI: 'Tarawa',
  KH: 'Phnom Penh',
  KN: 'Basseterre',
  KM: 'Moroni',
  ST: 'Sao Tome',
  SK: 'Bratislava',
  KR: 'Seoul',
  SI: 'Ljubljana',
  KP: 'Pyongyang',
  KW: 'Kuwait City',
  SN: 'Dakar',
  SM: 'San Marino',
  SL: 'Freetown',
  SC: 'Victoria',
  KZ: 'Astana',
  KY: 'George Town',
  SG: 'Singapur',
  SE: 'Stockholm',
  SD: 'Khartoum',
  DO: 'Santo Domingo',
  DM: 'Roseau',
  DJ: 'Djibouti',
  DK: 'Copenhagen',
  VG: 'Road Town',
  DE: 'Berlin',
  YE: 'Sanaa',
  DZ: 'Algiers',
  US: 'Washington',
  UY: 'Montevideo',
  YT: 'Mamoudzou',
  UM: '',
  LB: 'Beirut',
  LC: 'Castries',
  LA: 'Vientiane',
  TV: 'Funafuti',
  TW: 'Taipei',
  TT: 'Port of Spain',
  TR: 'Ankara',
  LK: 'Colombo',
  LI: 'Vaduz',
  LV: 'Riga',
  TO: "Nuku'alofa",
  LT: 'Vilnius',
  LU: 'Luxembourg',
  LR: 'Monrovia',
  LS: 'Maseru',
  TH: 'Bangkok',
  TF: 'Port-aux-Francais',
  TG: 'Lome',
  TD: "N'Djamena",
  TC: 'Cockburn Town',
  LY: 'Tripolis',
  VA: 'Vatican City',
  VC: 'Kingstown',
  AE: 'Abu Dhabi',
  AD: 'Andorra la Vella',
  AG: "St. John's",
  AF: 'Kabul',
  AI: 'The Valley',
  VI: 'Charlotte Amalie',
  IS: 'Reykjavik',
  IR: 'Tehran',
  AM: 'Yerevan',
  AL: 'Tirana',
  AO: 'Luanda',
  AQ: '',
  AS: 'Pago Pago',
  AR: 'Buenos Aires',
  AU: 'Canberra',
  AT: 'Vienna',
  AW: 'Oranjestad',
  IN: 'New Delhi',
  AX: 'Mariehamn',
  AZ: 'Baku',
  IE: 'Dublin',
  ID: 'Jakarta',
  UA: 'Kiev',
  QA: 'Doha',
  MZ: 'Maputo',
};

export const CountryCodes = [
  {
    code: 'AF',
    name: 'Afghanistan',
    dialCode: '+93',
    flag: 'https://www.countryflags.io/AF/flat/64.png',
  },
  {
    code: 'AX',
    name: 'Aland Islands',
    dialCode: '+358',
    flag: 'https://www.countryflags.io/AX/flat/64.png',
  },
  {
    code: 'AL',
    name: 'Albania',
    dialCode: '+355',
    flag: 'https://www.countryflags.io/AL/flat/64.png',
  },
  {
    code: 'DZ',
    name: 'Algeria',
    dialCode: '+213',
    flag: 'https://www.countryflags.io/DZ/flat/64.png',
  },
  {
    code: 'AS',
    name: 'American Samoa',
    dialCode: '+1684',
    flag: 'https://www.countryflags.io/AS/flat/64.png',
  },
  {
    code: 'AD',
    name: 'Andorra',
    dialCode: '+376',
    flag: 'https://www.countryflags.io/AD/flat/64.png',
  },
  {
    code: 'AO',
    name: 'Angola',
    dialCode: '+244',
    flag: 'https://www.countryflags.io/AO/flat/64.png',
  },
  {
    code: 'AI',
    name: 'Anguilla',
    dialCode: '+1264',
    flag: 'https://www.countryflags.io/AI/flat/64.png',
  },
  {
    code: 'AQ',
    name: 'Antarctica',
    dialCode: '+672',
    flag: 'https://www.countryflags.io/AQ/flat/64.png',
  },
  {
    code: 'AG',
    name: 'Antigua And Barbuda',
    dialCode: '+1268',
    flag: 'https://www.countryflags.io/AG/flat/64.png',
  },
  {
    code: 'AR',
    name: 'Argentina',
    dialCode: '+54',
    flag: 'https://www.countryflags.io/AR/flat/64.png',
  },
  {
    code: 'AM',
    name: 'Armenia',
    dialCode: '+374',
    flag: 'https://www.countryflags.io/AM/flat/64.png',
  },
  {
    code: 'AW',
    name: 'Aruba',
    dialCode: '+297',
    flag: 'https://www.countryflags.io/AW/flat/64.png',
  },
  {
    code: 'AU',
    name: 'Australia',
    dialCode: '+61',
    flag: 'https://www.countryflags.io/AU/flat/64.png',
  },
  {
    code: 'AT',
    name: 'Austria',
    dialCode: '+43',
    flag: 'https://www.countryflags.io/AT/flat/64.png',
  },
  {
    code: 'AZ',
    name: 'Azerbaijan',
    dialCode: '+994',
    flag: 'https://www.countryflags.io/AZ/flat/64.png',
  },
  {
    code: 'BS',
    name: 'Bahamas',
    dialCode: '+1242',
    flag: 'https://www.countryflags.io/BS/flat/64.png',
  },
  {
    code: 'BH',
    name: 'Bahrain',
    dialCode: '+973',
    flag: 'https://www.countryflags.io/BH/flat/64.png',
  },
  {
    code: 'BD',
    name: 'Bangladesh',
    dialCode: '+880',
    flag: 'https://www.countryflags.io/BD/flat/64.png',
  },
  {
    code: 'BB',
    name: 'Barbados',
    dialCode: '+1246',
    flag: 'https://www.countryflags.io/BB/flat/64.png',
  },
  {
    code: 'BY',
    name: 'Belarus',
    dialCode: '+375',
    flag: 'https://www.countryflags.io/BY/flat/64.png',
  },
  {
    code: 'BE',
    name: 'Belgium',
    dialCode: '+32',
    flag: 'https://www.countryflags.io/BE/flat/64.png',
  },
  {
    code: 'BZ',
    name: 'Belize',
    dialCode: '+501',
    flag: 'https://www.countryflags.io/BZ/flat/64.png',
  },
  {
    code: 'BJ',
    name: 'Benin',
    dialCode: '+229',
    flag: 'https://www.countryflags.io/BJ/flat/64.png',
  },
  {
    code: 'BM',
    name: 'Bermuda',
    dialCode: '+1441',
    flag: 'https://www.countryflags.io/BM/flat/64.png',
  },
  {
    code: 'BT',
    name: 'Bhutan',
    dialCode: '+975',
    flag: 'https://www.countryflags.io/BT/flat/64.png',
  },
  {
    code: 'BO',
    name: 'Bolivia',
    dialCode: '+591',
    flag: 'https://www.countryflags.io/BO/flat/64.png',
  },
  {
    code: 'BA',
    name: 'Bosnia And Herzegovina',
    dialCode: '+387',
    flag: 'https://www.countryflags.io/BA/flat/64.png',
  },
  {
    code: 'BW',
    name: 'Botswana',
    dialCode: '+267',
    flag: 'https://www.countryflags.io/BW/flat/64.png',
  },
  {
    code: 'BV',
    name: 'Bouvet Island',
    dialCode: '+47',
    flag: null,
  },
  {
    code: 'BR',
    name: 'Brazil',
    dialCode: '+55',
    flag: 'https://www.countryflags.io/BR/flat/64.png',
  },
  {
    code: 'IO',
    name: 'British Indian Ocean Territory',
    dialCode: '+246',
    flag: 'https://www.countryflags.io/IO/flat/64.png',
  },
  {
    code: 'BN',
    name: 'Brunei Darussalam',
    dialCode: '+673',
    flag: 'https://www.countryflags.io/BN/flat/64.png',
  },
  {
    code: 'BG',
    name: 'Bulgaria',
    dialCode: '+359',
    flag: 'https://www.countryflags.io/BG/flat/64.png',
  },
  {
    code: 'BF',
    name: 'Burkina Faso',
    dialCode: '+226',
    flag: 'https://www.countryflags.io/BF/flat/64.png',
  },
  {
    code: 'BI',
    name: 'Burundi',
    dialCode: '+257',
    flag: 'https://www.countryflags.io/BI/flat/64.png',
  },
  {
    code: 'KH',
    name: 'Cambodia',
    dialCode: '+855',
    flag: 'https://www.countryflags.io/KH/flat/64.png',
  },
  {
    code: 'CM',
    name: 'Cameroon',
    dialCode: '+237',
    flag: 'https://www.countryflags.io/CM/flat/64.png',
  },
  {
    code: 'CA',
    name: 'Canada',
    dialCode: '+1',
    flag: 'https://www.countryflags.io/CA/flat/64.png',
  },
  {
    code: 'CV',
    name: 'Cape Verde',
    dialCode: '+238',
    flag: 'https://www.countryflags.io/CV/flat/64.png',
  },
  {
    code: 'KY',
    name: 'Cayman Islands',
    dialCode: '+1345',
    flag: 'https://www.countryflags.io/KY/flat/64.png',
  },
  {
    code: 'CF',
    name: 'Central African Republic',
    dialCode: '+236',
    flag: 'https://www.countryflags.io/CF/flat/64.png',
  },
  {
    code: 'TD',
    name: 'Chad',
    dialCode: '+235',
    flag: 'https://www.countryflags.io/TD/flat/64.png',
  },
  {
    code: 'CL',
    name: 'Chile',
    dialCode: '+56',
    flag: 'https://www.countryflags.io/CL/flat/64.png',
  },
  {
    code: 'CN',
    name: 'China',
    dialCode: '+86',
    flag: 'https://www.countryflags.io/CN/flat/64.png',
  },
  {
    code: 'CX',
    name: 'Christmas Island',
    dialCode: '+61',
    flag: 'https://www.countryflags.io/CX/flat/64.png',
  },
  {
    code: 'CC',
    name: 'Cocos (Keeling) Islands',
    dialCode: '+61',
    flag: 'https://www.countryflags.io/CC/flat/64.png',
  },
  {
    code: 'CO',
    name: 'Colombia',
    dialCode: '+57',
    flag: 'https://www.countryflags.io/CO/flat/64.png',
  },
  {
    code: 'KM',
    name: 'Comoros',
    dialCode: '+269',
    flag: 'https://www.countryflags.io/KM/flat/64.png',
  },
  {
    code: 'CG',
    name: 'Congo',
    dialCode: '+242',
    flag: 'https://www.countryflags.io/CG/flat/64.png',
  },
  {
    code: 'CD',
    name: 'Congo, Democratic Republic',
    dialCode: '+243',
    flag: 'https://www.countryflags.io/CD/flat/64.png',
  },
  {
    code: 'CK',
    name: 'Cook Islands',
    dialCode: '+682',
    flag: 'https://www.countryflags.io/CK/flat/64.png',
  },
  {
    code: 'CR',
    name: 'Costa Rica',
    dialCode: '+506',
    flag: 'https://www.countryflags.io/CR/flat/64.png',
  },
  {
    code: 'CI',
    name: "Cote D'Ivoire",
    dialCode: '+225',
    flag: 'https://www.countryflags.io/CI/flat/64.png',
  },
  {
    code: 'HR',
    name: 'Croatia',
    dialCode: '+385',
    flag: 'https://www.countryflags.io/HR/flat/64.png',
  },
  {
    code: 'CU',
    name: 'Cuba',
    dialCode: '+53',
    flag: 'https://www.countryflags.io/CU/flat/64.png',
  },
  {
    code: 'CY',
    name: 'Cyprus',
    dialCode: '+357',
    flag: 'https://www.countryflags.io/CY/flat/64.png',
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    dialCode: '+420',
    flag: 'https://www.countryflags.io/CZ/flat/64.png',
  },
  {
    code: 'DK',
    name: 'Denmark',
    dialCode: '+45',
    flag: 'https://www.countryflags.io/DK/flat/64.png',
  },
  {
    code: 'DJ',
    name: 'Djibouti',
    dialCode: '+253',
    flag: 'https://www.countryflags.io/DJ/flat/64.png',
  },
  {
    code: 'DM',
    name: 'Dominica',
    dialCode: '+1767',
    flag: 'https://www.countryflags.io/DM/flat/64.png',
  },
  {
    code: 'DO',
    name: 'Dominican Republic',
    dialCode: '+1849',
    flag: 'https://www.countryflags.io/DO/flat/64.png',
  },
  {
    code: 'EC',
    name: 'Ecuador',
    dialCode: '+593',
    flag: 'https://www.countryflags.io/EC/flat/64.png',
  },
  {
    code: 'EG',
    name: 'Egypt',
    dialCode: '+20',
    flag: 'https://www.countryflags.io/EG/flat/64.png',
  },
  {
    code: 'SV',
    name: 'El Salvador',
    dialCode: '+503',
    flag: 'https://www.countryflags.io/SV/flat/64.png',
  },
  {
    code: 'GQ',
    name: 'Equatorial Guinea',
    dialCode: '+240',
    flag: 'https://www.countryflags.io/GQ/flat/64.png',
  },
  {
    code: 'ER',
    name: 'Eritrea',
    dialCode: '+291',
    flag: 'https://www.countryflags.io/ER/flat/64.png',
  },
  {
    code: 'EE',
    name: 'Estonia',
    dialCode: '+372',
    flag: 'https://www.countryflags.io/EE/flat/64.png',
  },
  {
    code: 'ET',
    name: 'Ethiopia',
    dialCode: '+251',
    flag: 'https://www.countryflags.io/ET/flat/64.png',
  },
  {
    code: 'FK',
    name: 'Falkland Islands (Malvinas)',
    dialCode: '+500',
    flag: 'https://www.countryflags.io/FK/flat/64.png',
  },
  {
    code: 'FO',
    name: 'Faroe Islands',
    dialCode: '+298',
    flag: 'https://www.countryflags.io/FO/flat/64.png',
  },
  {
    code: 'FJ',
    name: 'Fiji',
    dialCode: '+679',
    flag: 'https://www.countryflags.io/FJ/flat/64.png',
  },
  {
    code: 'FI',
    name: 'Finland',
    dialCode: '+358',
    flag: 'https://www.countryflags.io/FI/flat/64.png',
  },
  {
    code: 'FR',
    name: 'France',
    dialCode: '+33',
    flag: 'https://www.countryflags.io/FR/flat/64.png',
  },
  {
    code: 'GF',
    name: 'French Guiana',
    dialCode: '+594',
    flag: 'https://www.countryflags.io/GF/flat/64.png',
  },
  {
    code: 'PF',
    name: 'French Polynesia',
    dialCode: '+689',
    flag: 'https://www.countryflags.io/PF/flat/64.png',
  },
  {
    code: 'TF',
    name: 'French Southern Territories',
    dialCode: '+262',
    flag: null,
  },
  {
    code: 'GA',
    name: 'Gabon',
    dialCode: '+241',
    flag: 'https://www.countryflags.io/GA/flat/64.png',
  },
  {
    code: 'GM',
    name: 'Gambia',
    dialCode: '+220',
    flag: 'https://www.countryflags.io/GM/flat/64.png',
  },
  {
    code: 'GE',
    name: 'Georgia',
    dialCode: '+995',
    flag: 'https://www.countryflags.io/GE/flat/64.png',
  },
  {
    code: 'DE',
    name: 'Germany',
    dialCode: '+49',
    flag: 'https://www.countryflags.io/DE/flat/64.png',
  },
  {
    code: 'GH',
    name: 'Ghana',
    dialCode: '+233',
    flag: 'https://www.countryflags.io/GH/flat/64.png',
  },
  {
    code: 'GI',
    name: 'Gibraltar',
    dialCode: '+350',
    flag: 'https://www.countryflags.io/GI/flat/64.png',
  },
  {
    code: 'GR',
    name: 'Greece',
    dialCode: '+30',
    flag: 'https://www.countryflags.io/GR/flat/64.png',
  },
  {
    code: 'GL',
    name: 'Greenland',
    dialCode: '+299',
    flag: 'https://www.countryflags.io/GL/flat/64.png',
  },
  {
    code: 'GD',
    name: 'Grenada',
    dialCode: '+1473',
    flag: 'https://www.countryflags.io/GD/flat/64.png',
  },
  {
    code: 'GP',
    name: 'Guadeloupe',
    dialCode: '+590',
    flag: 'https://www.countryflags.io/GP/flat/64.png',
  },
  {
    code: 'GU',
    name: 'Guam',
    dialCode: '+1671',
    flag: 'https://www.countryflags.io/GU/flat/64.png',
  },
  {
    code: 'GT',
    name: 'Guatemala',
    dialCode: '+502',
    flag: 'https://www.countryflags.io/GT/flat/64.png',
  },
  {
    code: 'GG',
    name: 'Guernsey',
    dialCode: '+44',
    flag: 'https://www.countryflags.io/GG/flat/64.png',
  },
  {
    code: 'GN',
    name: 'Guinea',
    dialCode: '+224',
    flag: 'https://www.countryflags.io/GN/flat/64.png',
  },
  {
    code: 'GW',
    name: 'Guinea-Bissau',
    dialCode: '+245',
    flag: 'https://www.countryflags.io/GW/flat/64.png',
  },
  {
    code: 'GY',
    name: 'Guyana',
    dialCode: '+592',
    flag: 'https://www.countryflags.io/GY/flat/64.png',
  },
  {
    code: 'HT',
    name: 'Haiti',
    dialCode: '+509',
    flag: 'https://www.countryflags.io/HT/flat/64.png',
  },
  {
    code: 'HM',
    name: 'Heard Island & Mcdonald Islands',
    dialCode: '011',
    flag: null,
  },
  {
    code: 'VA',
    name: 'Holy See (Vatican City State)',
    dialCode: '+379',
    flag: 'https://www.countryflags.io/VA/flat/64.png',
  },
  {
    code: 'HN',
    name: 'Honduras',
    dialCode: '+504',
    flag: 'https://www.countryflags.io/HN/flat/64.png',
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    dialCode: '+852',
    flag: 'https://www.countryflags.io/HK/flat/64.png',
  },
  {
    code: 'HU',
    name: 'Hungary',
    dialCode: '+36',
    flag: 'https://www.countryflags.io/HU/flat/64.png',
  },
  {
    code: 'IS',
    name: 'Iceland',
    dialCode: '+354',
    flag: 'https://www.countryflags.io/IS/flat/64.png',
  },
  {
    code: 'IN',
    name: 'India',
    dialCode: '+91',
    flag: 'https://www.countryflags.io/IN/flat/64.png',
  },
  {
    code: 'ID',
    name: 'Indonesia',
    dialCode: '+62',
    flag: 'https://www.countryflags.io/ID/flat/64.png',
  },
  {
    code: 'IR',
    name: 'Iran, Islamic Republic Of',
    dialCode: '+98',
    flag: 'https://www.countryflags.io/IR/flat/64.png',
  },
  {
    code: 'IQ',
    name: 'Iraq',
    dialCode: '+964',
    flag: 'https://www.countryflags.io/IQ/flat/64.png',
  },
  {
    code: 'IE',
    name: 'Ireland',
    dialCode: '+353',
    flag: 'https://www.countryflags.io/IE/flat/64.png',
  },
  {
    code: 'IM',
    name: 'Isle Of Man',
    dialCode: '+44',
    flag: 'https://www.countryflags.io/IM/flat/64.png',
  },
  {
    code: 'IL',
    name: 'Israel',
    dialCode: '+972',
    flag: 'https://www.countryflags.io/IL/flat/64.png',
  },
  {
    code: 'IT',
    name: 'Italy',
    dialCode: '+39',
    flag: 'https://www.countryflags.io/IT/flat/64.png',
  },
  {
    code: 'JM',
    name: 'Jamaica',
    dialCode: '+1876',
    flag: 'https://www.countryflags.io/JM/flat/64.png',
  },
  {
    code: 'JP',
    name: 'Japan',
    dialCode: '+81',
    flag: 'https://www.countryflags.io/JP/flat/64.png',
  },
  {
    code: 'JE',
    name: 'Jersey',
    dialCode: '+44',
    flag: 'https://www.countryflags.io/JE/flat/64.png',
  },
  {
    code: 'JO',
    name: 'Jordan',
    dialCode: '+962',
    flag: 'https://www.countryflags.io/JO/flat/64.png',
  },
  {
    code: 'KZ',
    name: 'Kazakhstan',
    dialCode: '+77',
    flag: 'https://www.countryflags.io/KZ/flat/64.png',
  },
  {
    code: 'KE',
    name: 'Kenya',
    dialCode: '+254',
    flag: 'https://www.countryflags.io/KE/flat/64.png',
  },
  {
    code: 'KI',
    name: 'Kiribati',
    dialCode: '+686',
    flag: 'https://www.countryflags.io/KI/flat/64.png',
  },
  {
    code: 'KR',
    name: 'Korea',
    dialCode: '+82',
    flag: 'https://www.countryflags.io/KR/flat/64.png',
  },
  {
    code: 'KW',
    name: 'Kuwait',
    dialCode: '+965',
    flag: 'https://www.countryflags.io/KW/flat/64.png',
  },
  {
    code: 'KG',
    name: 'Kyrgyzstan',
    dialCode: '+996',
    flag: 'https://www.countryflags.io/KG/flat/64.png',
  },
  {
    code: 'LA',
    name: "Lao People's Democratic Republic",
    dialCode: '+856',
    flag: 'https://www.countryflags.io/LA/flat/64.png',
  },
  {
    code: 'LV',
    name: 'Latvia',
    dialCode: '+371',
    flag: 'https://www.countryflags.io/LV/flat/64.png',
  },
  {
    code: 'LB',
    name: 'Lebanon',
    dialCode: '+961',
    flag: 'https://www.countryflags.io/LB/flat/64.png',
  },
  {
    code: 'LS',
    name: 'Lesotho',
    dialCode: '+266',
    flag: 'https://www.countryflags.io/LS/flat/64.png',
  },
  {
    code: 'LR',
    name: 'Liberia',
    dialCode: '+231',
    flag: 'https://www.countryflags.io/LR/flat/64.png',
  },
  {
    code: 'LY',
    name: 'Libyan Arab Jamahiriya',
    dialCode: '+218',
    flag: 'https://www.countryflags.io/LY/flat/64.png',
  },
  {
    code: 'LI',
    name: 'Liechtenstein',
    dialCode: '+423',
    flag: 'https://www.countryflags.io/LI/flat/64.png',
  },
  {
    code: 'LT',
    name: 'Lithuania',
    dialCode: '+370',
    flag: 'https://www.countryflags.io/LT/flat/64.png',
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    dialCode: '+352',
    flag: 'https://www.countryflags.io/LU/flat/64.png',
  },
  {
    code: 'MO',
    name: 'Macao',
    dialCode: '+853',
    flag: 'https://www.countryflags.io/MO/flat/64.png',
  },
  {
    code: 'MK',
    name: 'Macedonia',
    dialCode: '+389',
    flag: 'https://www.countryflags.io/MK/flat/64.png',
  },
  {
    code: 'MG',
    name: 'Madagascar',
    dialCode: '+261',
    flag: 'https://www.countryflags.io/MG/flat/64.png',
  },
  {
    code: 'MW',
    name: 'Malawi',
    dialCode: '+265',
    flag: 'https://www.countryflags.io/MW/flat/64.png',
  },
  {
    code: 'MY',
    name: 'Malaysia',
    dialCode: '+60',
    flag: 'https://www.countryflags.io/MY/flat/64.png',
  },
  {
    code: 'MV',
    name: 'Maldives',
    dialCode: '+960',
    flag: 'https://www.countryflags.io/MV/flat/64.png',
  },
  {
    code: 'ML',
    name: 'Mali',
    dialCode: '+223',
    flag: 'https://www.countryflags.io/ML/flat/64.png',
  },
  {
    code: 'MT',
    name: 'Malta',
    dialCode: '+356',
    flag: 'https://www.countryflags.io/MT/flat/64.png',
  },
  {
    code: 'MH',
    name: 'Marshall Islands',
    dialCode: '+692',
    flag: 'https://www.countryflags.io/MH/flat/64.png',
  },
  {
    code: 'MQ',
    name: 'Martinique',
    dialCode: '+596',
    flag: 'https://www.countryflags.io/MQ/flat/64.png',
  },
  {
    code: 'MR',
    name: 'Mauritania',
    dialCode: '+222',
    flag: 'https://www.countryflags.io/MR/flat/64.png',
  },
  {
    code: 'MU',
    name: 'Mauritius',
    dialCode: '+230',
    flag: 'https://www.countryflags.io/MU/flat/64.png',
  },
  {
    code: 'YT',
    name: 'Mayotte',
    dialCode: '+262',
    flag: 'https://www.countryflags.io/YT/flat/64.png',
  },
  {
    code: 'MX',
    name: 'Mexico',
    dialCode: '+52',
    flag: 'https://www.countryflags.io/MX/flat/64.png',
  },
  {
    code: 'FM',
    name: 'Micronesia, Federated States Of',
    dialCode: '+691',
    flag: 'https://www.countryflags.io/FM/flat/64.png',
  },
  {
    code: 'MD',
    name: 'Moldova',
    dialCode: '+373',
    flag: 'https://www.countryflags.io/MD/flat/64.png',
  },
  {
    code: 'MC',
    name: 'Monaco',
    dialCode: '+377',
    flag: 'https://www.countryflags.io/MC/flat/64.png',
  },
  {
    code: 'MN',
    name: 'Mongolia',
    dialCode: '+976',
    flag: 'https://www.countryflags.io/MN/flat/64.png',
  },
  {
    code: 'ME',
    name: 'Montenegro',
    dialCode: '+382',
    flag: 'https://www.countryflags.io/ME/flat/64.png',
  },
  {
    code: 'MS',
    name: 'Montserrat',
    dialCode: '+1664',
    flag: 'https://www.countryflags.io/MS/flat/64.png',
  },
  {
    code: 'MA',
    name: 'Morocco',
    dialCode: '+212',
    flag: 'https://www.countryflags.io/MA/flat/64.png',
  },
  {
    code: 'MZ',
    name: 'Mozambique',
    dialCode: '+258',
    flag: 'https://www.countryflags.io/MZ/flat/64.png',
  },
  {
    code: 'MM',
    name: 'Myanmar',
    dialCode: '+95',
    flag: 'https://www.countryflags.io/MM/flat/64.png',
  },
  {
    code: 'NA',
    name: 'Namibia',
    dialCode: '+264',
    flag: 'https://www.countryflags.io/NA/flat/64.png',
  },
  {
    code: 'NR',
    name: 'Nauru',
    dialCode: '+674',
    flag: 'https://www.countryflags.io/NR/flat/64.png',
  },
  {
    code: 'NP',
    name: 'Nepal',
    dialCode: '+977',
    flag: 'https://www.countryflags.io/NP/flat/64.png',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    dialCode: '+31',
    flag: 'https://www.countryflags.io/NL/flat/64.png',
  },
  {
    code: 'AN',
    name: 'Netherlands Antilles',
    dialCode: '+599',
    flag: 'https://www.countryflags.io/AN/flat/64.png',
  },
  {
    code: 'NC',
    name: 'New Caledonia',
    dialCode: '+687',
    flag: 'https://www.countryflags.io/NC/flat/64.png',
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    dialCode: '+64',
    flag: 'https://www.countryflags.io/NZ/flat/64.png',
  },
  {
    code: 'NI',
    name: 'Nicaragua',
    dialCode: '+505',
    flag: 'https://www.countryflags.io/NI/flat/64.png',
  },
  {
    code: 'NE',
    name: 'Niger',
    dialCode: '+227',
    flag: 'https://www.countryflags.io/NE/flat/64.png',
  },
  {
    code: 'NG',
    name: 'Nigeria',
    dialCode: '+234',
    flag: 'https://www.countryflags.io/NG/flat/64.png',
  },
  {
    code: 'NU',
    name: 'Niue',
    dialCode: '+683',
    flag: 'https://www.countryflags.io/NU/flat/64.png',
  },
  {
    code: 'NF',
    name: 'Norfolk Island',
    dialCode: '+672',
    flag: 'https://www.countryflags.io/NF/flat/64.png',
  },
  {
    code: 'MP',
    name: 'Northern Mariana Islands',
    dialCode: '+1670',
    flag: 'https://www.countryflags.io/MP/flat/64.png',
  },
  {
    code: 'NO',
    name: 'Norway',
    dialCode: '+47',
    flag: 'https://www.countryflags.io/NO/flat/64.png',
  },
  {
    code: 'OM',
    name: 'Oman',
    dialCode: '+968',
    flag: 'https://www.countryflags.io/OM/flat/64.png',
  },
  {
    code: 'PK',
    name: 'Pakistan',
    dialCode: '+92',
    flag: 'https://www.countryflags.io/PK/flat/64.png',
  },
  {
    code: 'PW',
    name: 'Palau',
    dialCode: '+680',
    flag: 'https://www.countryflags.io/PW/flat/64.png',
  },
  {
    code: 'PS',
    name: 'Palestinian Territory, Occupied',
    dialCode: '+970',
    flag: 'https://www.countryflags.io/PS/flat/64.png',
  },
  {
    code: 'PA',
    name: 'Panama',
    dialCode: '+507',
    flag: 'https://www.countryflags.io/PA/flat/64.png',
  },
  {
    code: 'PG',
    name: 'Papua New Guinea',
    dialCode: '+675',
    flag: 'https://www.countryflags.io/PG/flat/64.png',
  },
  {
    code: 'PY',
    name: 'Paraguay',
    dialCode: '+595',
    flag: 'https://www.countryflags.io/PY/flat/64.png',
  },
  {
    code: 'PE',
    name: 'Peru',
    dialCode: '+51',
    flag: 'https://www.countryflags.io/PE/flat/64.png',
  },
  {
    code: 'PH',
    name: 'Philippines',
    dialCode: '+63',
    flag: 'https://www.countryflags.io/PH/flat/64.png',
  },
  {
    code: 'PN',
    name: 'Pitcairn',
    dialCode: '+872',
    flag: 'https://www.countryflags.io/PN/flat/64.png',
  },
  {
    code: 'PL',
    name: 'Poland',
    dialCode: '+48',
    flag: 'https://www.countryflags.io/PL/flat/64.png',
  },
  {
    code: 'PT',
    name: 'Portugal',
    dialCode: '+351',
    flag: 'https://www.countryflags.io/PT/flat/64.png',
  },
  {
    code: 'PR',
    name: 'Puerto Rico',
    dialCode: '+1939',
    flag: 'https://www.countryflags.io/PR/flat/64.png',
  },
  {
    code: 'QA',
    name: 'Qatar',
    dialCode: '+974',
    flag: 'https://www.countryflags.io/QA/flat/64.png',
  },
  {
    code: 'RE',
    name: 'Reunion',
    dialCode: '+262',
    flag: 'https://www.countryflags.io/RE/flat/64.png',
  },
  {
    code: 'RO',
    name: 'Romania',
    dialCode: '+40',
    flag: 'https://www.countryflags.io/RO/flat/64.png',
  },
  {
    code: 'RU',
    name: 'Russian Federation',
    dialCode: '+7',
    flag: 'https://www.countryflags.io/RU/flat/64.png',
  },
  {
    code: 'RW',
    name: 'Rwanda',
    dialCode: '+250',
    flag: 'https://www.countryflags.io/RW/flat/64.png',
  },
  {
    code: 'BL',
    name: 'Saint Barthelemy',
    dialCode: '+590',
    flag: 'https://www.countryflags.io/BL/flat/64.png',
  },
  {
    code: 'SH',
    name: 'Saint Helena',
    dialCode: '+290',
    flag: 'https://www.countryflags.io/SH/flat/64.png',
  },
  {
    code: 'KN',
    name: 'Saint Kitts And Nevis',
    dialCode: '+1869',
    flag: 'https://www.countryflags.io/KN/flat/64.png',
  },
  {
    code: 'LC',
    name: 'Saint Lucia',
    dialCode: '+1758',
    flag: 'https://www.countryflags.io/LC/flat/64.png',
  },
  {
    code: 'MF',
    name: 'Saint Martin',
    dialCode: '+590',
    flag: 'https://www.countryflags.io/MF/flat/64.png',
  },
  {
    code: 'PM',
    name: 'Saint Pierre And Miquelon',
    dialCode: '+508',
    flag: 'https://www.countryflags.io/PM/flat/64.png',
  },
  {
    code: 'VC',
    name: 'Saint Vincent And Grenadines',
    dialCode: '+1784',
    flag: 'https://www.countryflags.io/VC/flat/64.png',
  },
  {
    code: 'WS',
    name: 'Samoa',
    dialCode: '+685',
    flag: 'https://www.countryflags.io/WS/flat/64.png',
  },
  {
    code: 'SM',
    name: 'San Marino',
    dialCode: '+378',
    flag: 'https://www.countryflags.io/SM/flat/64.png',
  },
  {
    code: 'ST',
    name: 'Sao Tome And Principe',
    dialCode: '+239',
    flag: 'https://www.countryflags.io/ST/flat/64.png',
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    dialCode: '+966',
    flag: 'https://www.countryflags.io/SA/flat/64.png',
  },
  {
    code: 'SN',
    name: 'Senegal',
    dialCode: '+221',
    flag: 'https://www.countryflags.io/SN/flat/64.png',
  },
  {
    code: 'RS',
    name: 'Serbia',
    dialCode: '+381',
    flag: 'https://www.countryflags.io/RS/flat/64.png',
  },
  {
    code: 'SC',
    name: 'Seychelles',
    dialCode: '+248',
    flag: 'https://www.countryflags.io/SC/flat/64.png',
  },
  {
    code: 'SL',
    name: 'Sierra Leone',
    dialCode: '+232',
    flag: 'https://www.countryflags.io/SL/flat/64.png',
  },
  {
    code: 'SG',
    name: 'Singapore',
    dialCode: '+65',
    flag: 'https://www.countryflags.io/SG/flat/64.png',
  },
  {
    code: 'SK',
    name: 'Slovakia',
    dialCode: '+421',
    flag: 'https://www.countryflags.io/SK/flat/64.png',
  },
  {
    code: 'SI',
    name: 'Slovenia',
    dialCode: '+386',
    flag: 'https://www.countryflags.io/SI/flat/64.png',
  },
  {
    code: 'SB',
    name: 'Solomon Islands',
    dialCode: '+677',
    flag: 'https://www.countryflags.io/SB/flat/64.png',
  },
  {
    code: 'SO',
    name: 'Somalia',
    dialCode: '+252',
    flag: 'https://www.countryflags.io/SO/flat/64.png',
  },
  {
    code: 'ZA',
    name: 'South Africa',
    dialCode: '+27',
    flag: 'https://www.countryflags.io/ZA/flat/64.png',
  },
  {
    code: 'GS',
    name: 'South Georgia And Sandwich Isl.',
    dialCode: '+500',
    flag: 'https://www.countryflags.io/GS/flat/64.png',
  },
  {
    code: 'ES',
    name: 'Spain',
    dialCode: '+34',
    flag: 'https://www.countryflags.io/ES/flat/64.png',
  },
  {
    code: 'LK',
    name: 'Sri Lanka',
    dialCode: '+94',
    flag: 'https://www.countryflags.io/LK/flat/64.png',
  },
  {
    code: 'SD',
    name: 'Sudan',
    dialCode: '+249',
    flag: 'https://www.countryflags.io/SD/flat/64.png',
  },
  {
    code: 'SR',
    name: 'Suriname',
    dialCode: '+597',
    flag: 'https://www.countryflags.io/SR/flat/64.png',
  },
  {
    code: 'SJ',
    name: 'Svalbard And Jan Mayen',
    dialCode: '+47',
    flag: 'https://www.countryflags.io/SJ/flat/64.png',
  },
  {
    code: 'SZ',
    name: 'Swaziland',
    dialCode: '+268',
    flag: 'https://www.countryflags.io/SZ/flat/64.png',
  },
  {
    code: 'SE',
    name: 'Sweden',
    dialCode: '+46',
    flag: 'https://www.countryflags.io/SE/flat/64.png',
  },
  {
    code: 'CH',
    name: 'Switzerland',
    dialCode: '+41',
    flag: 'https://www.countryflags.io/CH/flat/64.png',
  },
  {
    code: 'SY',
    name: 'Syrian Arab Republic',
    dialCode: '+963',
    flag: 'https://www.countryflags.io/SY/flat/64.png',
  },
  {
    code: 'TW',
    name: 'Taiwan',
    dialCode: '+886',
    flag: 'https://www.countryflags.io/TW/flat/64.png',
  },
  {
    code: 'TJ',
    name: 'Tajikistan',
    dialCode: '+992',
    flag: 'https://www.countryflags.io/TJ/flat/64.png',
  },
  {
    code: 'TZ',
    name: 'Tanzania',
    dialCode: '+255',
    flag: 'https://www.countryflags.io/TZ/flat/64.png',
  },
  {
    code: 'TH',
    name: 'Thailand',
    dialCode: '+66',
    flag: 'https://www.countryflags.io/TH/flat/64.png',
  },
  {
    code: 'TL',
    name: 'Timor-Leste',
    dialCode: '+670',
    flag: 'https://www.countryflags.io/TL/flat/64.png',
  },
  {
    code: 'TG',
    name: 'Togo',
    dialCode: '+228',
    flag: 'https://www.countryflags.io/TG/flat/64.png',
  },
  {
    code: 'TK',
    name: 'Tokelau',
    dialCode: '+690',
    flag: 'https://www.countryflags.io/TK/flat/64.png',
  },
  {
    code: 'TO',
    name: 'Tonga',
    dialCode: '+676',
    flag: 'https://www.countryflags.io/TO/flat/64.png',
  },
  {
    code: 'TT',
    name: 'Trinidad And Tobago',
    dialCode: '+1868',
    flag: 'https://www.countryflags.io/TT/flat/64.png',
  },
  {
    code: 'TN',
    name: 'Tunisia',
    dialCode: '+216',
    flag: 'https://www.countryflags.io/TN/flat/64.png',
  },
  {
    code: 'TR',
    name: 'Turkey',
    dialCode: '+90',
    flag: 'https://www.countryflags.io/TR/flat/64.png',
  },
  {
    code: 'TM',
    name: 'Turkmenistan',
    dialCode: '+993',
    flag: 'https://www.countryflags.io/TM/flat/64.png',
  },
  {
    code: 'TC',
    name: 'Turks And Caicos Islands',
    dialCode: '+1649',
    flag: 'https://www.countryflags.io/TC/flat/64.png',
  },
  {
    code: 'TV',
    name: 'Tuvalu',
    dialCode: '+688',
    flag: 'https://www.countryflags.io/TV/flat/64.png',
  },
  {
    code: 'UG',
    name: 'Uganda',
    dialCode: '+256',
    flag: 'https://www.countryflags.io/UG/flat/64.png',
  },
  {
    code: 'UA',
    name: 'Ukraine',
    dialCode: '+380',
    flag: 'https://www.countryflags.io/UA/flat/64.png',
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    dialCode: '+971',
    flag: 'https://www.countryflags.io/AE/flat/64.png',
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    dialCode: '+44',
    flag: 'https://www.countryflags.io/GB/flat/64.png',
  },
  {
    code: 'US',
    name: 'United States',
    dialCode: '+1',
    flag: 'https://www.countryflags.io/US/flat/64.png',
  },
  {
    code: 'UM',
    name: 'United States Outlying Islands',
    dialCode: '+246',
    flag: null,
  },
  {
    code: 'UY',
    name: 'Uruguay',
    dialCode: '+598',
    flag: 'https://www.countryflags.io/UY/flat/64.png',
  },
  {
    code: 'UZ',
    name: 'Uzbekistan',
    dialCode: '+998',
    flag: 'https://www.countryflags.io/UZ/flat/64.png',
  },
  {
    code: 'VU',
    name: 'Vanuatu',
    dialCode: '+678',
    flag: 'https://www.countryflags.io/VU/flat/64.png',
  },
  {
    code: 'VE',
    name: 'Venezuela',
    dialCode: '+58',
    flag: 'https://www.countryflags.io/VE/flat/64.png',
  },
  {
    code: 'VN',
    name: 'Viet Nam',
    dialCode: '+84',
    flag: 'https://www.countryflags.io/VN/flat/64.png',
  },
  {
    code: 'VG',
    name: 'Virgin Islands, British',
    dialCode: '+1284',
    flag: 'https://www.countryflags.io/VG/flat/64.png',
  },
  {
    code: 'VI',
    name: 'Virgin Islands, U.S.',
    dialCode: '+1340',
    flag: 'https://www.countryflags.io/VI/flat/64.png',
  },
  {
    code: 'WF',
    name: 'Wallis And Futuna',
    dialCode: '+681',
    flag: 'https://www.countryflags.io/WF/flat/64.png',
  },
  {
    code: 'EH',
    name: 'Western Sahara',
    dialCode: '+212',
    flag: null,
  },
  {
    code: 'YE',
    name: 'Yemen',
    dialCode: '+967',
    flag: 'https://www.countryflags.io/YE/flat/64.png',
  },
  {
    code: 'ZM',
    name: 'Zambia',
    dialCode: '+260',
    flag: 'https://www.countryflags.io/ZM/flat/64.png',
  },
  {
    code: 'ZW',
    name: 'Zimbabwe',
    dialCode: '+263',
    flag: 'https://www.countryflags.io/ZW/flat/64.png',
  },
];
