export const REPOSITORY = {
  USER: 'USER',
  BCRYPT_ROUNDS: 10,
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: '1d',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: '7d',
  CACHE_SETTING_EXPIRATION_TIME: 0,
  REDIS_TOKEN_EXPIRATION_TIME_IN_SECONDS: 604800,
  NOTIFICATION_SETTINGS: 'NOTIFICATION_SETTINGS',
};
